/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Books = {
  _id: string;
  _type: "books";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  author?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  genre?: string;
};

export type Quotes = {
  _id: string;
  _type: "quotes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  quote?: string;
  author?: string;
  maxwidth?: "max-w-xl" | "max-w-2xl" | "max-w-3xl" | "max-w-4xl";
};

export type Inspirations = {
  _id: string;
  _type: "inspirations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  title?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  impact?: string;
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Philosophy = {
  _id: string;
  _type: "philosophy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  philosophy?: string;
  imageLight?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageDark?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Projects = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  longDescription?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  year?: number;
  liveUrl?: string;
  githubUrl?: string;
  gitlabUrl?: string;
  featured?: boolean;
  category?: "frontend" | "backend" | "fullstack";
  status?: "completed" | "ongoing";
  teamType?: "solo" | "team";
  teamCount?: number;
  applications?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "technologies";
  }>;
  highlights?: Array<string>;
};

export type Extracurriculars = {
  _id: string;
  _type: "extracurriculars";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  icon?: string;
  description?: string;
  highlights?: Array<string>;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  institution?: string;
  period?: string;
  achievements?: Array<string>;
};

export type Experiences = {
  _id: string;
  _type: "experiences";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  company?: string;
  period?: string;
  description?: string;
  achievements?: Array<string>;
  history?: Array<{
    title?: string;
    company?: string;
    period?: string;
    _key: string;
  }>;
};

export type Skills = {
  _id: string;
  _type: "skills";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: "Frontend" | "Backend" | "Other Tools";
  description?: string;
  skills?: Array<{
    name?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "technologies";
    };
    variant?: "primary" | "accent" | "ghost";
    _key: string;
  }>;
};

export type Technologies = {
  _id: string;
  _type: "technologies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  variant?: "primary" | "accent" | "neutral";
};

export type Achievements = {
  _id: string;
  _type: "achievements";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  highlight?: string;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Books | Quotes | Inspirations | Philosophy | Projects | Extracurriculars | Education | Experiences | Skills | Technologies | Achievements | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: src/sanity/queries/about.queries.ts
// Variable: skillsQuery
// Query: *    [_type == "skills"] | order(_createdAt asc) {        title,        description,        skills[] {'name': name->name, variant}    }
export type SkillsQueryResult = Array<{
  title: "Backend" | "Frontend" | "Other Tools" | null;
  description: string | null;
  skills: Array<{
    name: string | null;
    variant: "accent" | "ghost" | "primary" | null;
  }> | null;
}>;
// Variable: experiencesQuery
// Query: *    [_type=="experiences"]|order(_createdAt desc)    {title, company, period, description, achievements, history}
export type ExperiencesQueryResult = Array<{
  title: string | null;
  company: string | null;
  period: string | null;
  description: string | null;
  achievements: Array<string> | null;
  history: Array<{
    title?: string;
    company?: string;
    period?: string;
    _key: string;
  }> | null;
}>;
// Variable: educationQuery
// Query: *    [_type=="education"]|order(_createdAt desc)    {title, description, institution, period, achievements}
export type EducationQueryResult = Array<{
  title: string | null;
  description: string | null;
  institution: string | null;
  period: string | null;
  achievements: Array<string> | null;
}>;
// Variable: extracurricularsQuery
// Query: *    [_type=="extracurriculars"]|order(_createdAt asc)    {title, description, icon, highlights}
export type ExtracurricularsQueryResult = Array<{
  title: string | null;
  description: string | null;
  icon: string | null;
  highlights: Array<string> | null;
}>;

// Source: src/sanity/queries/landing.queries.ts
// Variable: achievementsQuery
// Query: *    [_type=="achievements"]|order(_createdAt asc)    {title, highlight, description}
export type AchievementsQueryResult = Array<{
  title: string | null;
  highlight: string | null;
  description: string | null;
}>;

// Source: src/sanity/queries/projects.queries.ts
// Variable: projectsQuery
// Query: *    [_type == "projects"]    | order(year desc, _createdAt desc)    {      title,      description,      longDescription,      image,      year,      liveUrl,      githubUrl,      gitlabUrl,      featured,      category,      status,      teamType,      teamCount,      applications,      technologies[]->{name, variant},      highlights    }
export type ProjectsQueryResult = Array<{
  title: string | null;
  description: string | null;
  longDescription: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  year: number | null;
  liveUrl: string | null;
  githubUrl: string | null;
  gitlabUrl: string | null;
  featured: boolean | null;
  category: "backend" | "frontend" | "fullstack" | null;
  status: "completed" | "ongoing" | null;
  teamType: "solo" | "team" | null;
  teamCount: number | null;
  applications: Array<string> | null;
  technologies: Array<{
    name: string | null;
    variant: "accent" | "neutral" | "primary" | null;
  }> | null;
  highlights: Array<string> | null;
}>;

// Source: src/sanity/queries/values.queries.ts
// Variable: philosophyQuery
// Query: *    [_type=="philosophy"][0]    {title, philosophy, imageLight, imageDark}
export type PhilosophyQueryResult = {
  title: string | null;
  philosophy: string | null;
  imageLight: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageDark: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;
// Variable: inspirationsQuery
// Query: *    [_type=="inspirations"]|order(_createdAt asc)    {name, title, image, impact}
export type InspirationsQueryResult = Array<{
  name: string | null;
  title: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  impact: string | null;
}>;
// Variable: quotesQuery
// Query: *    [_type=="quotes"]|order(_createdAt asc)    {heading, quote, author, maxwidth}
export type QuotesQueryResult = Array<{
  heading: string | null;
  quote: string | null;
  author: string | null;
  maxwidth: "max-w-2xl" | "max-w-3xl" | "max-w-4xl" | "max-w-xl" | null;
}>;
// Variable: booksQuery
// Query: *    [_type=="books"]|order(_createdAt asc)    {title, author, image, genre}
export type BooksQueryResult = Array<{
  title: string | null;
  author: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*\n    [_type == \"skills\"] | order(_createdAt asc) {\n        title,\n        description,\n        skills[] {'name': name->name, variant}\n    }\n": SkillsQueryResult;
    "*\n    [_type==\"experiences\"]|order(_createdAt desc)\n    {title, company, period, description, achievements, history}\n": ExperiencesQueryResult;
    "*\n    [_type==\"education\"]|order(_createdAt desc)\n    {title, description, institution, period, achievements}\n": EducationQueryResult;
    "*\n    [_type==\"extracurriculars\"]|order(_createdAt asc)\n    {title, description, icon, highlights}\n": ExtracurricularsQueryResult;
    "*\n    [_type==\"achievements\"]|order(_createdAt asc)\n    {title, highlight, description}\n": AchievementsQueryResult;
    "*\n    [_type == \"projects\"]\n    | order(year desc, _createdAt desc)\n    {\n      title,\n      description,\n      longDescription,\n      image,\n      year,\n      liveUrl,\n      githubUrl,\n      gitlabUrl,\n      featured,\n      category,\n      status,\n      teamType,\n      teamCount,\n      applications,\n      technologies[]->{name, variant},\n      highlights\n    }  \n": ProjectsQueryResult;
    "*\n    [_type==\"philosophy\"][0]\n    {title, philosophy, imageLight, imageDark}\n": PhilosophyQueryResult;
    "*\n    [_type==\"inspirations\"]|order(_createdAt asc)\n    {name, title, image, impact}\n": InspirationsQueryResult;
    "*\n    [_type==\"quotes\"]|order(_createdAt asc)\n    {heading, quote, author, maxwidth}\n": QuotesQueryResult;
    "*\n    [_type==\"books\"]|order(_createdAt asc)\n    {title, author, image, genre}\n": BooksQueryResult;
  }
}
